// Generated by `gwylio schema` from the Pydantic models registered in
// backend/src/gwylio/infrastructure/config/schemas.py. Do not edit by hand.

/** An organisation that publishes or is reported on. */
export interface ActorConfig {
	id: string;
	name: string;
	kind: ActorKind;
	/** The lane where this actor is usually found. */
	lane: string;
	/** Bare host, such as gov.wales. */
	domain?: string | null;
}

/** The kind of an organisation. */
export type ActorKind = "government" | "legislature" | "regulator" | "public_body" | "research" | "ngo" | "business" | "union" | "media" | "international" | "other";

/** config/reference/actors.json: the actor catalogue. */
export interface ActorsFile {
	notes?: string | null;
	actors: ActorConfig[];
}

/** One candidate: a gated, deduplicated hit, one per canonical URL in the run. */
export interface CandidateEntry {
	candidate_id: string;
	status: CandidateStatus;
	/** The URL as first found, before canonicalising. */
	url: string;
	/** The canonical URL: no scheme, www, fragment or tracking. */
	canonical_url: string;
	title: string;
	snippet: string;
	published_on: string | null;
	/** The run that first recorded this URL. */
	first_seen_run_id: string;
	/** The watched source, or null for the open web. */
	source_id: string | null;
	lane: string;
	discipline: Discipline;
	/** The query whose hit found this URL first. */
	query_id: string;
	/** Hints from the queries; not tags. */
	requirement_hints: string[];
	/** Hints from the queries; not tags. */
	topic_hints: string[];
	trusted: boolean;
}

/** What the collector knew about a candidate's canonical URL when it found it. */
export type CandidateStatus = "new" | "seen_before" | "reinforcement";

/** data/candidates/<run_id>.json: everything one completed scan run found. */
export interface CandidatesFile {
	/** Always gwylio.candidates/1. */
	format: "gwylio.candidates/1";
	/** A scan run id. */
	run_id: string;
	/** complete, or aborted when a collector failed: then nothing was kept. */
	run_status?: "complete" | "aborted";
	instrument_version: string;
	instrument_hash: string;
	generated_at: string;
	started_at: string;
	finished_at: string;
	disciplines_run: Discipline[];
	max_requests_per_run: number;
	requests_made: number;
	budget_exhausted: boolean;
	funnel: FunnelCounts;
	/** What the run says about itself, such as the budget. */
	notes: string[];
	/** Soft failures the collectors reported. */
	warnings: string[];
	candidates: CandidateEntry[];
	reinforcements: ReinforcementEntry[];
	sightings: SightingEntry[];
}

/** The state of one requirement in the picture. */
export type CoverageStatus = "covered" | "thin" | "quiet" | "blind_spot";

/** The kind of collection a collector performs. */
export type Discipline = "osint_web" | "osint_feed" | "osint_site" | "osint_academic" | "geoint" | "sensor";

/**
 * How many hits survived each stage of the run.
 *
 * raw = dropped_own + dropped_negative + dropped_unrelated + passed, and
 * unique = new + seen_before + reinforcements.
 */
export interface FunnelCounts {
	raw: number;
	dropped_own: number;
	dropped_negative: number;
	dropped_unrelated: number;
	/** Hits that passed every gate and reached deduplication. */
	passed: number;
	/** Candidates: passed hits grouped by canonical URL. */
	unique: number;
	seen_before: number;
	new: number;
	reinforcements: number;
}

/** config/gating.json: own domains and relevance tokens for the gates. */
export interface GatingFile {
	notes?: string | null;
	/** The organisation's own domains: hits on them are dropped. */
	own_domains: string[];
	/** Lower-case words or phrases that make an untrusted hit relevant. */
	relevance_tokens: string[];
	/** Places of these kinds add their English and Welsh names as tokens. */
	relevance_place_kinds?: PlaceKind[];
}

/** What a requirement group stands for. */
export type GroupKind = "impact" | "wbo";

/** A named threat to the Welsh environment. */
export interface HazardConfig {
	id: string;
	name: string;
	/** A node id on the hazard-families taxonomy axis. */
	family: string;
	note?: string | null;
}

/** config/reference/hazards.json: the hazard catalogue. */
export interface HazardsFile {
	notes?: string | null;
	hazards: HazardConfig[];
}

/** config/instrument.json: the versioned query instrument. */
export interface InstrumentFile {
	notes?: string | null;
	/** Such as 2026.10.0. */
	version: string;
	/** sha256 of the canonical JSON of every field except notes and this one. */
	content_hash: string;
	global_negative_terms?: string[];
	/** The request budget of one scan run. */
	max_requests_per_run: number;
	queries: QueryConfig[];
}

/** Where we look: a grouping of sources under one lens. */
export interface LaneConfig {
	id: string;
	name: string;
	lens: Lens;
	/** One sentence on what the lane watches. */
	description: string;
}

/** config/lanes.json: the collection lanes. */
export interface LanesFile {
	notes?: string | null;
	lanes: LaneConfig[];
}

/** The three viewpoints the commission asked for; every lane sits under one. */
export type Lens = "government" | "partnership_society" | "international";

/** How a candidate was matched to an existing intelligence report. */
export type MatchedBy = "url" | "title";

/** What a taxonomy node stands for. */
export type NodeKind = "ecosystem" | "resource" | "hazard_family";

/** A named location. */
export interface PlaceConfig {
	id: string;
	name: string;
	/** The Welsh name, where different. */
	welsh_name?: string | null;
	kind: PlaceKind;
	/** The id of the containing place. */
	parent?: string | null;
	/** Latitude and longitude in decimal degrees (WGS 84). */
	centroid?: [number, number] | null;
}

/** The kind of a named place. */
export type PlaceKind = "nation" | "region" | "area" | "river_basin" | "settlement" | "site";

/** config/reference/places.json: the place catalogue. */
export interface PlacesFile {
	notes?: string | null;
	places: PlaceConfig[];
}

/** One query in the instrument. */
export interface QueryConfig {
	id: string;
	discipline: Discipline;
	/** Where the query looks; feed queries read this lane's feeds. */
	lane: string;
	/** Query text; site and feed queries OR-join quoted phrases. */
	text: string;
	/** Requirement ids the hits may bear on; hints, not tags. */
	requirement_hints?: string[];
	/** Topic ids; hints, not tags. */
	topic_hints?: string[];
	/** Terms that drop a hit, after the global ones. */
	negative_terms?: string[];
	/** osint_site only: the sources to restrict the query to. */
	site_source_ids?: string[];
}

/** A candidate that matched an existing intelligence report at collection time. */
export interface ReinforcementEntry {
	candidate_id: string;
	report_id: string;
	matched_by: MatchedBy;
}

/**
 * The Admiralty reliability of a source, A (best) to F (cannot be judged).
 *
 * Reliability belongs to the source, never to one report: the analyst judges
 * credibility (1 to 6) per report, and the two together make the grading.
 */
export type Reliability = "A" | "B" | "C" | "D" | "E" | "F";

/** One Priority Intelligence Requirement (PIR). */
export interface RequirementConfig {
	/** Display code, e.g. SI1. */
	code: string;
	id: string;
	name: string;
	/** At most six words, for tiles and tables. */
	short: string;
	scanability: Scanability;
	scanability_note: string;
	keywords?: string[];
	/** Taxonomy node ids this requirement should touch. */
	expected_coverage?: string[];
	metric_sources?: string[];
	/** True while the indicator is still being developed. */
	development?: boolean;
}

/** An impact statement or a well-being objective grouping requirements. */
export interface RequirementGroupConfig {
	id: string;
	kind: GroupKind;
	name: string;
	statement?: string | null;
	/** Requirement ids in this group. */
	members: string[];
	/** Ids of other groups in the set this one maps to. */
	related_groups?: string[];
	note?: string | null;
}

/** config/requirement_sets/<id>.json: one requirement set. */
export interface RequirementSetFile {
	notes?: string | null;
	/** Must equal the file name without .json. */
	id: string;
	name: string;
	version: string;
	source_doc: string;
	requirements: RequirementConfig[];
	groups?: RequirementGroupConfig[];
}

/** How far public, indexed sources can see a requirement at all. */
export type Scanability = "high" | "medium" | "low" | "none";

/** One hit that became part of a candidate. */
export interface SightingEntry {
	sighting_id: string;
	candidate_id: string;
	source_id: string | null;
	query_id: string;
	discipline: Discipline;
}

/** A watchlist entry: where hits come from, with a default reliability. */
export interface SourceConfig {
	id: string;
	name: string;
	/** Bare host; hits are matched to sources by exact domain. */
	domain: string;
	/** Required for osint_feed sources. */
	feed_url?: string | null;
	discipline: Discipline;
	lane: string;
	/** The actor that publishes on this source. */
	actor: string;
	/** Admiralty reliability, A to F. */
	reliability: Reliability;
	/** A trusted source passes the relevance gate on domain alone. */
	trusted: boolean;
	/** Whether site queries may sweep this source's domain. */
	site_pass: boolean;
	status?: SourceStatus;
	/** A date, YYYY-MM-DD. */
	added_on: string;
	notes?: string | null;
}

/** Whether a source is watched. */
export type SourceStatus = "active" | "parked" | "retired";

/** config/sources.json: the source watchlist. */
export interface SourcesFile {
	notes?: string | null;
	sources: SourceConfig[];
}

/** One dimension of the taxonomy. */
export interface TaxonomyAxisConfig {
	id: string;
	name: string;
	nodes: TaxonomyNodeConfig[];
}

/** config/taxonomy.json: the classification axes. */
export interface TaxonomyFile {
	notes?: string | null;
	axes: TaxonomyAxisConfig[];
}

/** One value on a taxonomy axis. */
export interface TaxonomyNodeConfig {
	/** Unique across the whole taxonomy. */
	id: string;
	name: string;
	kind: NodeKind;
	note?: string | null;
}

/** A subject area used to hint what a query or report is about. */
export interface TopicConfig {
	id: string;
	name: string;
	note?: string | null;
}

/** config/reference/topics.json: the topic catalogue. */
export interface TopicsFile {
	notes?: string | null;
	topics: TopicConfig[];
}
