// Generated by `gwylio schema` from the Pydantic models registered in
// backend/src/gwylio/infrastructure/config/schemas.py. Do not edit by hand.

/** An organisation that publishes or is reported on. */
export interface ActorConfig {
	id: string;
	name: string;
	kind: ActorKind;
	/** The lane where this actor is usually found. */
	lane: string;
	/** Bare host, such as gov.wales. */
	domain?: string | null;
}

/** The kind of an organisation. */
export type ActorKind = "government" | "legislature" | "regulator" | "public_body" | "research" | "ngo" | "business" | "union" | "media" | "international" | "other";

/** config/reference/actors.json: the actor catalogue. */
export interface ActorsFile {
	notes?: string | null;
	actors: ActorConfig[];
}

/** Which way the report bears on one requirement. */
export interface AssessmentEntry {
	/** A requirement id from skill/REFERENCE.md, such as si4. */
	requirement_id: string;
	direction: Direction;
}

/** Where a report goes next. */
export type Bucket = "brief" | "follow_up" | "watch" | "park";

/** One candidate: a gated, deduplicated hit, one per canonical URL in the run. */
export interface CandidateEntry {
	candidate_id: string;
	status: CandidateStatus;
	/** The URL as first found, before canonicalising. */
	url: string;
	/** The canonical URL: no scheme, www, fragment or tracking. */
	canonical_url: string;
	title: string;
	snippet: string;
	published_on: string | null;
	/** The run that first recorded this URL. */
	first_seen_run_id: string;
	/** The watched source, or null for the open web. */
	source_id: string | null;
	lane: string;
	discipline: Discipline;
	/** The query whose hit found this URL first. */
	query_id: string;
	/** Hints from the queries; not tags. */
	requirement_hints: string[];
	/** Hints from the queries; not tags. */
	topic_hints: string[];
	trusted: boolean;
}

/** What the collector knew about a candidate's canonical URL when it found it. */
export type CandidateStatus = "new" | "seen_before" | "reinforcement";

/** data/candidates/<run_id>.json: everything one completed scan run found. */
export interface CandidatesFile {
	/** Always gwylio.candidates/1. */
	format: "gwylio.candidates/1";
	/** A scan run id. */
	run_id: string;
	/** complete, or aborted when a collector failed: then nothing was kept. */
	run_status?: "complete" | "aborted";
	instrument_version: string;
	instrument_hash: string;
	generated_at: string;
	started_at: string;
	finished_at: string;
	disciplines_run: Discipline[];
	max_requests_per_run: number;
	requests_made: number;
	budget_exhausted: boolean;
	funnel: FunnelCounts;
	/** What the run says about itself, such as the budget. */
	notes: string[];
	/** Soft failures the collectors reported. */
	warnings: string[];
	candidates: CandidateEntry[];
	reinforcements: ReinforcementEntry[];
	sightings: SightingEntry[];
}

/** Words both products share. */
export interface CommonCopy {
	/** Month names, January first. */
	months: string[];
	/** Lead line naming the requirement set. */
	set_line: string;
	/** Lead line naming the period and the render date. */
	period_line: string;
	/** What a list with nothing in it says. */
	none: string;
	/** Joins items in a running list, such as ', '. */
	list_separator: string;
	/** One item of a running count, such as 'supports 3'. */
	count_pair: string;
	/** One assessment on a report line. */
	direction_tag: string;
	/** A share written as a percentage. */
	share: string;
	/** A table cell for true. */
	yes: string;
	/** A table cell for false. */
	no: string;
	/** Column heading for reports with no resolvable lane. */
	unattributed: string;
	/** Table heading: the measure counted. */
	header_measure: string;
	/** Table heading: the count. */
	header_count: string;
	/** Table heading: the requirement. */
	header_requirement: string;
	/** Table heading: the row total. */
	header_total: string;
	/** Table heading: the coverage status. */
	header_status: string;
	/** Table heading: the taxonomy node. */
	header_node: string;
	/** Table heading: requirements expecting the node. */
	header_expected: string;
	/** Table heading: active reports. */
	header_reports: string;
	/** Table heading: the direction. */
	header_direction: string;
	/** Table heading: the credibility digit. */
	header_credibility: string;
	/** Table heading: the wording of a value. */
	header_label: string;
	/** The standing sentence that a blind spot is not quiet. */
	blind_spot_rule: string;
	/** The standing sentence that counts of reports are not counts of impact. */
	undercount: string;
	directions: DirectionCopy;
	states: StateCopy;
	statuses: CoverageCopy;
	scanability: ScanabilityCopy;
	credibility: CredibilityCopy;
}

/** config/copy.json: every heading and standing sentence the products use. */
export interface Copy {
	/** Free notes for whoever edits the copy. */
	notes?: string | null;
	common: CommonCopy;
	method: MethodCopy;
	intsum: IntsumCopy;
	strategic: StrategicCopy;
}

/** How each coverage status reads in a product. */
export interface CoverageCopy {
	/** Label for covered. */
	covered: string;
	/** Label for thin. */
	thin: string;
	/** Label for quiet. */
	quiet: string;
	/** Label for blind spot. */
	blind_spot: string;
}

/** The state of one requirement in the picture. */
export type CoverageStatus = "covered" | "thin" | "quiet" | "blind_spot";

/**
 * The Admiralty credibility of one report's information, 1 (best) to 6 (cannot be judged).
 *
 * The analyst judges credibility per report; the source's reliability is
 * fixed by the watchlist. The two together make the grading, such as B2.
 */
export type Credibility = 1 | 2 | 3 | 4 | 5 | 6;

/** The Admiralty wording for each credibility digit. */
export interface CredibilityCopy {
	/** Credibility 1. */
	one: string;
	/** Credibility 2. */
	two: string;
	/** Credibility 3. */
	three: string;
	/** Credibility 4. */
	four: string;
	/** Credibility 5. */
	five: string;
	/** Credibility 6. */
	six: string;
}

/** config/datecheck.json: the rules gwylio datecheck applies. */
export interface DatecheckFile {
	notes?: string | null;
	/** Future-framed phrases that rot once their date passes, matched as words. */
	future_phrases: string[];
	/** A verification older than this many days is stale. */
	stale_after_days?: number;
}

/** Which way a report bears on one requirement. */
export type Direction = "supports" | "threatens" | "neutral" | "informs_baseline";

/** How each direction reads in a product. */
export interface DirectionCopy {
	/** Label for the threatens direction. */
	threatens: string;
	/** Label for the neutral (two-way) direction. */
	neutral: string;
	/** Label for the informs_baseline direction. */
	informs_baseline: string;
	/** Label for the supports direction. */
	supports: string;
}

/** The kind of collection a collector performs. */
export type Discipline = "osint_web" | "osint_feed" | "osint_site" | "osint_academic" | "geoint" | "sensor";

/** The fate of one candidate. */
export interface DispositionEntry {
	candidate_id: string;
	outcome: DispositionOutcome;
	/** One sentence: which part of the promotion test decided. */
	reason: string;
	/** promoted: the new report; reinforcement: the report it reinforces; duplicate: optionally, the report it duplicates. */
	report_id?: string | null;
}

/** The fate the analyst gives one candidate in a submission. */
export type DispositionOutcome = "promoted" | "rejected" | "duplicate" | "deferred" | "reinforcement";

/** One report the sweep faded, and the reason recorded in its history. */
export interface FadeEntry {
	report_id: string;
	change: string;
}

/** A date check finding kind: a heading and the sentence that explains it. */
export interface FindingCopy {
	/** Heading for this kind of finding. */
	heading: string;
	/** One sentence on what this kind of finding means. */
	meaning: string;
}

/** What the date check found wrong with a report. */
export type FindingKind = "passed_horizon" | "future_language" | "stale_verification" | "never_verified";

/**
 * How many hits survived each stage of the run.
 *
 * raw = dropped_own + dropped_negative + dropped_unrelated + passed, and
 * unique = new + seen_before + reinforcements.
 */
export interface FunnelCounts {
	raw: number;
	dropped_own: number;
	dropped_negative: number;
	dropped_unrelated: number;
	/** Hits that passed every gate and reached deduplication. */
	passed: number;
	/** Candidates: passed hits grouped by canonical URL. */
	unique: number;
	seen_before: number;
	new: number;
	reinforcements: number;
}

/** config/gating.json: own domains and relevance tokens for the gates. */
export interface GatingFile {
	notes?: string | null;
	/** The organisation's own domains: hits on them are dropped. */
	own_domains: string[];
	/** Lower-case words or phrases that make an untrusted hit relevant. */
	relevance_tokens: string[];
	/** Places of these kinds add their English and Welsh names as tokens. */
	relevance_place_kinds?: PlaceKind[];
}

/** What a requirement group stands for. */
export type GroupKind = "impact" | "wbo";

/** A named threat to the Welsh environment. */
export interface HazardConfig {
	id: string;
	name: string;
	/** A node id on the hazard-families taxonomy axis. */
	family: string;
	note?: string | null;
}

/** config/reference/hazards.json: the hazard catalogue. */
export interface HazardsFile {
	notes?: string | null;
	hazards: HazardConfig[];
}

/** What one history entry records. */
export type HistoryKind = "created" | "sighted" | "state_changed" | "verified" | "updated" | "imported" | "faded" | "revived";

/** Where a report is in the indications and warnings lifecycle. */
export type IndicatorState = "emerging" | "tracking" | "reinforced" | "matured" | "faded" | "parked";

/** config/instrument.json: the versioned query instrument. */
export interface InstrumentFile {
	notes?: string | null;
	/** Such as 2026.10.0. */
	version: string;
	/** sha256 of the canonical JSON of every field except notes and this one. */
	content_hash: string;
	global_negative_terms?: string[];
	/** The request budget of one scan run. */
	max_requests_per_run: number;
	queries: QueryConfig[];
}

/** The operational intelligence summary (INTSUM). */
export interface IntsumCopy {
	/** Title of the INTSUM. */
	title: string;
	/** Lead sentence on what the INTSUM is for. */
	purpose: string;
	/** Heading of the summary. */
	summary_heading: string;
	/** Sentence: new reports in the period. */
	summary_new: string;
	/** Sentence: lifecycle state changes in the period. */
	summary_state_changes: string;
	/** Sentence: reports faded in the period. */
	summary_faded: string;
	/** Sentence: reports verified in the period. */
	summary_verified: string;
	/** Sentence: assessments on the reports that moved, by direction. */
	summary_directions: string;
	/** Summary table row: new reports. */
	measure_new: string;
	/** Summary table row: state changes. */
	measure_state_changes: string;
	/** Summary table row: faded. */
	measure_faded: string;
	/** Summary table row: verified. */
	measure_verified: string;
	/** Summary table row: assessments in one direction. */
	measure_direction: string;
	/** Heading of the reports that moved. */
	moved_heading: string;
	/** Sentence introducing the per objective lists. */
	moved_intro: string;
	/** Subheading for one well-being objective. */
	group_heading: string;
	/** Subheading for reports outside every well-being objective. */
	outside_heading: string;
	/** What an objective with nothing moving says. */
	group_empty: string;
	/** One report in a list. */
	report_line: string;
	/** Heading of the quiet requirements and blind spots. */
	quiet_heading: string;
	/** Sentence introducing the requirements with no movement. */
	quiet_intro: string;
	/** One requirement with no movement. */
	quiet_line: string;
	/** What the section says when every requirement moved. */
	quiet_none: string;
	/** Heading of the date check findings. */
	verification_heading: string;
	/** Sentence counting the date check findings. */
	verification_intro: string;
	/** What the section says when the date check found nothing. */
	verification_none: string;
	/** One finding. */
	finding_line: string;
	passed_horizon: FindingCopy;
	future_language: FindingCopy;
	stale_verification: FindingCopy;
	never_verified: FindingCopy;
}

/** Where we look: a grouping of sources under one lens. */
export interface LaneConfig {
	id: string;
	name: string;
	lens: Lens;
	/** One sentence on what the lane watches. */
	description: string;
}

/** config/lanes.json: the collection lanes. */
export interface LanesFile {
	notes?: string | null;
	lanes: LaneConfig[];
}

/** The three viewpoints the commission asked for; every lane sits under one. */
export type Lens = "government" | "partnership_society" | "international";

/** A three-point score: low, medium or high. */
export type Level = "low" | "medium" | "high";

/** How a candidate was matched to an existing intelligence report. */
export type MatchedBy = "url" | "title";

/** The method note both products end with. */
export interface MethodCopy {
	/** Heading of the method note. */
	heading: string;
	/** How many scan runs started in the period. */
	runs: string;
	/** What the note says when no run started in the period. */
	no_runs: string;
	/** Runs table heading: run id. */
	header_run: string;
	/** Runs table heading: start date. */
	header_started: string;
	/** Runs table heading: instrument version. */
	header_instrument: string;
	/** Runs table heading: raw hits. */
	header_raw: string;
	/** Runs table heading: unique candidates. */
	header_unique: string;
	/** Runs table heading: new candidates. */
	header_new: string;
	/** Runs table heading: reinforcements. */
	header_reinforcements: string;
	/** Runs table heading: requests made. */
	header_requests: string;
	/** Runs table heading: budget exhausted. */
	header_budget: string;
	/** Credibility table heading: reports created in the period. */
	header_reports: string;
	/** Dispositions of the period's candidates. */
	dispositions: string;
	/** Reports created in the period and the non-government share. */
	promotions: string;
	/** What the note says when no report was created in the period. */
	no_promotions: string;
	/** Introduces the credibility table for the period's reports. */
	credibility: string;
	/** The instrument versions the period's runs used. */
	instrument: string;
	/** The current instrument version, when no run used one in the period. */
	instrument_current: string;
	/** The requirements this tool cannot see. */
	blind_spots: string;
	/** What the note says when no requirement is a blind spot. */
	no_blind_spots: string;
	/** The standing sentence on what the queries would never find. */
	streetlight: string;
}

/** What a taxonomy node stands for. */
export type NodeKind = "ecosystem" | "resource" | "hazard_family";

/** The dates a product covers, inclusive, and its label. */
export interface PeriodModel {
	/** A date, YYYY-MM-DD. */
	start: string;
	/** A date, YYYY-MM-DD. */
	end: string;
	/** YYYY-MM for a month, YYYY for a year. */
	label: string;
}

/** A named location. */
export interface PlaceConfig {
	id: string;
	name: string;
	/** The Welsh name, where different. */
	welsh_name?: string | null;
	kind: PlaceKind;
	/** The id of the containing place. */
	parent?: string | null;
	/** Latitude and longitude in decimal degrees (WGS 84). */
	centroid?: [number, number] | null;
}

/** The kind of a named place. */
export type PlaceKind = "nation" | "region" | "area" | "river_basin" | "settlement" | "site";

/** config/reference/places.json: the place catalogue. */
export interface PlacesFile {
	notes?: string | null;
	places: PlaceConfig[];
}

/** One line of history the report had before it entered Gwylio (the legacy import). */
export interface PriorHistoryEntry {
	/** A date, YYYY-MM-DD. */
	on: string;
	change: string;
}

/** data/products/<stem>.json: one rendered product's structure. */
export interface ProductFile {
	/** Always gwylio.product/1. */
	format: "gwylio.product/1";
	id: string;
	level: ProductLevel;
	requirement_set_id: string;
	period: PeriodModel;
	/** A date, YYYY-MM-DD. */
	generated_on: string;
	title: string;
	lead: string[];
	sections: SectionModel[];
	report_ids: string[];
	method_note: string;
	/** The Markdown file beside this one. */
	markdown_file: string;
}

/** The level a product serves: the annual picture, the monthly summary, or an alert. */
export type ProductLevel = "strategic" | "operational" | "tactical";

/** A new intelligence report. Reliability, lane and appearances are not the analyst's. */
export interface PromotionEntry {
	/** A new kebab-case report id. */
	id: string;
	/** The candidate this report was promoted from, if any. */
	from_candidate?: string | null;
	title: string;
	/** The http or https URL. */
	url: string;
	/** The watched source, or null when unwatched. */
	source_id: string | null;
	/** Who published it, as a reader would name them. */
	source_name: string;
	/** The actor, when catalogued. */
	actor_id?: string | null;
	/** Where it was found; required when source_id is null, else the source's. */
	lane?: string | null;
	report_type: ReportType;
	/** Admiralty credibility, 1 to 6. */
	credibility: Credibility;
	/** Required when source_id is null; ignored otherwise (the source decides). */
	reliability_if_unknown_source?: Reliability | null;
	assessments: AssessmentEntry[];
	topics?: string[];
	hazards?: string[];
	places?: string[];
	scores: ScoresEntry;
	bucket: Bucket;
	event_horizon?: string | null;
	last_verified?: string | null;
	summary: string;
	notes?: string;
	owner?: string | null;
	/** Create the report as matured or parked instead of emerging. */
	state_override?: "matured" | "parked" | null;
	/** History from before Gwylio, carried as imported entries (legacy import). */
	prior_history?: PriorHistoryEntry[];
	/** The text of the creation history entry, if not the default. */
	creation_note?: string | null;
}

/** One query in the instrument. */
export interface QueryConfig {
	id: string;
	discipline: Discipline;
	/** Where the query looks; feed queries read this lane's feeds. */
	lane: string;
	/** Query text; site and feed queries OR-join quoted phrases. */
	text: string;
	/** Requirement ids the hits may bear on; hints, not tags. */
	requirement_hints?: string[];
	/** Topic ids; hints, not tags. */
	topic_hints?: string[];
	/** Terms that drop a hit, after the global ones. */
	negative_terms?: string[];
	/** osint_site only: the sources to restrict the query to. */
	site_source_ids?: string[];
}

/** A candidate that matched an existing intelligence report at collection time. */
export interface ReinforcementEntry {
	candidate_id: string;
	report_id: string;
	matched_by: MatchedBy;
}

/** A candidate whose sightings count for an existing report. */
export interface ReinforcementLink {
	report_id: string;
	candidate_id: string;
}

/**
 * The Admiralty reliability of a source, A (best) to F (cannot be judged).
 *
 * Reliability belongs to the source, never to one report: the analyst judges
 * credibility (1 to 6) per report, and the two together make the grading.
 */
export type Reliability = "A" | "B" | "C" | "D" | "E" | "F";

/** What kind of development an intelligence report describes. */
export type ReportType = "policy" | "legislation" | "research" | "data_release" | "funding" | "partnership" | "international" | "legal" | "environmental" | "market" | "incident";

/** One Priority Intelligence Requirement (PIR). */
export interface RequirementConfig {
	/** Display code, e.g. SI1. */
	code: string;
	id: string;
	name: string;
	/** At most six words, for tiles and tables. */
	short: string;
	scanability: Scanability;
	scanability_note: string;
	keywords?: string[];
	/** Taxonomy node ids this requirement should touch. */
	expected_coverage?: string[];
	metric_sources?: string[];
	/** True while the indicator is still being developed. */
	development?: boolean;
}

/** An impact statement or a well-being objective grouping requirements. */
export interface RequirementGroupConfig {
	id: string;
	kind: GroupKind;
	name: string;
	statement?: string | null;
	/** Requirement ids in this group. */
	members: string[];
	/** Ids of other groups in the set this one maps to. */
	related_groups?: string[];
	note?: string | null;
}

/** config/requirement_sets/<id>.json: one requirement set. */
export interface RequirementSetFile {
	notes?: string | null;
	/** Must equal the file name without .json. */
	id: string;
	name: string;
	version: string;
	source_doc: string;
	requirements: RequirementConfig[];
	groups?: RequirementGroupConfig[];
}

/** How far public, indexed sources can see a requirement at all. */
export type Scanability = "high" | "medium" | "low" | "none";

/** How each scanability value reads in a product. */
export interface ScanabilityCopy {
	/** Label for high scanability. */
	high: string;
	/** Label for medium scanability. */
	medium: string;
	/** Label for low scanability. */
	low: string;
	/** Label for no scanability. */
	none: string;
}

/** The analyst's scores for a report. */
export interface ScoresEntry {
	/** How strong the evidence on the page is. */
	evidence: Level;
	novelty: Level;
	confidence: Level;
	potential_impact: Level;
	time_horizon: TimeHorizon;
}

/** One section: heading, paragraphs, tables and bullets, rendered in that order. */
export interface SectionModel {
	heading: string;
	/** 2 for a section, 3 for a subsection. */
	depth: number;
	body: string[];
	tables: TableModel[];
	bullets: string[];
}

/** How urgent a finding is: ``act`` before the report is quoted again, ``warn`` to check. */
export type Severity = "warn" | "act";

/** One hit that became part of a candidate. */
export interface SightingEntry {
	sighting_id: string;
	candidate_id: string;
	source_id: string | null;
	query_id: string;
	discipline: Discipline;
}

/** A watchlist entry: where hits come from, with a default reliability. */
export interface SourceConfig {
	id: string;
	name: string;
	/** Bare host; hits are matched to sources by exact domain. */
	domain: string;
	/** Required for osint_feed sources. */
	feed_url?: string | null;
	discipline: Discipline;
	lane: string;
	/** The actor that publishes on this source. */
	actor: string;
	/** Admiralty reliability, A to F. */
	reliability: Reliability;
	/** A trusted source passes the relevance gate on domain alone. */
	trusted: boolean;
	/** Whether site queries may sweep this source's domain. */
	site_pass: boolean;
	status?: SourceStatus;
	/** A date, YYYY-MM-DD. */
	added_on: string;
	notes?: string | null;
}

/** Whether a source is watched. */
export type SourceStatus = "active" | "parked" | "retired";

/** config/sources.json: the source watchlist. */
export interface SourcesFile {
	notes?: string | null;
	sources: SourceConfig[];
}

/** How each indicator state reads in a product. */
export interface StateCopy {
	/** Label for emerging. */
	emerging: string;
	/** Label for tracking. */
	tracking: string;
	/** Label for reinforced. */
	reinforced: string;
	/** Label for matured. */
	matured: string;
	/** Label for faded. */
	faded: string;
	/** Label for parked. */
	parked: string;
}

/** The strategic assessment: the annual picture per requirement set. */
export interface StrategicCopy {
	/** Title of the strategic assessment. */
	title: string;
	/** Heading of the purpose. */
	purpose_heading: string;
	/** Paragraphs on what the assessment is for. */
	purpose: string[];
	/** Heading of the standing picture. */
	picture_heading: string;
	/** Sentence introducing the standing picture. */
	picture_intro: string;
	/** Subheading for one requirement. */
	requirement_heading: string;
	/** Coverage status of a requirement. */
	status_line: string;
	/** Active reports by direction. */
	directions_line: string;
	/** Active reports by state. */
	states_line: string;
	/** Grading spread of the active reports. */
	grading_line: string;
	/** Matured reports kept as settled context. */
	matured_line: string;
	/** Scanability, with the requirement's note verbatim. */
	scanability_line: string;
	/** Sentence introducing the highest potential impact reports. */
	top_intro: string;
	/** One report among the highest potential impact. */
	top_line: string;
	/** Potential impact: high. */
	impact_high: string;
	/** Potential impact: medium. */
	impact_medium: string;
	/** Potential impact: low. */
	impact_low: string;
	/** Heading of the questions per well-being objective. */
	questions_heading: string;
	/** Sentence on what the questions are and are not. */
	questions_intro: string;
	/** Subheading for one well-being objective. */
	group_heading: string;
	/** One question drawn from a threatening or two-way report. */
	question: string;
	/** What an objective with no threat or two-way report says. */
	questions_none: string;
	/** Heading of the coverage audit. */
	coverage_heading: string;
	/** Sentence introducing the coverage audit. */
	coverage_intro: string;
	/** Subheading of the requirement by lane matrix. */
	lane_matrix_heading: string;
	/** Sentence explaining the requirement by lane matrix. */
	lane_matrix_note: string;
	/** Subheading of one taxonomy axis. */
	taxonomy_heading: string;
	/** Sentence explaining the taxonomy counts. */
	taxonomy_note: string;
}

/** data/submissions/<run_id>__<n>.json: the analyst's judgements on one run, or none. */
export interface Submission {
	/** Always gwylio.submission/1. */
	schema: "gwylio.submission/1";
	/** The run judged, or null for out-of-run. */
	run_id: string | null;
	analyst: string;
	/** Such as 2026.10. */
	rubric_version: string;
	/** A date, YYYY-MM-DD. */
	received_on: string;
	dispositions?: DispositionEntry[];
	promotions?: PromotionEntry[];
	updates?: UpdateEntry[];
	reinforcements?: ReinforcementLink[];
	verifications?: VerificationEntry[];
	/** How the run was judged: what was read and skipped. */
	method_note: string;
}

/** data/sweeps/<on>__<n>.json: the reports one sweep faded. */
export interface SweepFile {
	/** Always gwylio.sweep/1. */
	format: "gwylio.sweep/1";
	/** The day the sweep ran: the date of each fade. */
	on: string;
	/** How many submissions had been ingested when the sweep ran. */
	after_submissions: number;
	faded: FadeEntry[];
}

/** A table: header cells, then rows of cells as wide as the header. */
export interface TableModel {
	headers: string[];
	rows: Array<string[]>;
}

/** One dimension of the taxonomy. */
export interface TaxonomyAxisConfig {
	id: string;
	name: string;
	nodes: TaxonomyNodeConfig[];
}

/** config/taxonomy.json: the classification axes. */
export interface TaxonomyFile {
	notes?: string | null;
	axes: TaxonomyAxisConfig[];
}

/** One value on a taxonomy axis. */
export interface TaxonomyNodeConfig {
	/** Unique across the whole taxonomy. */
	id: string;
	name: string;
	kind: NodeKind;
	note?: string | null;
}

/** When a report's consequences are expected to land. */
export type TimeHorizon = "immediate" | "near_term" | "medium_term" | "long_term";

/** A subject area used to hint what a query or report is about. */
export interface TopicConfig {
	id: string;
	name: string;
	note?: string | null;
}

/** config/reference/topics.json: the topic catalogue. */
export interface TopicsFile {
	notes?: string | null;
	topics: TopicConfig[];
}

/** Analyst changes to an existing report. */
export interface UpdateEntry {
	report_id: string;
	/** Only state (matured or parked), bucket, owner, notes, summary, title, event_horizon and independent_confirmation (true) may be set. */
	set: Record<string, unknown>;
	/** Why: the history entry text. */
	change: string;
}

/** The analyst checked the report's claims against the world. */
export interface VerificationEntry {
	report_id: string;
	/** A date, YYYY-MM-DD. */
	verified_on: string;
	note: string;
}

/** What a source's yield says about its place on the watchlist. */
export type YieldReading = "earning_its_place" | "high_volume_no_promotions" | "low_volume" | "silent";
