"""Drift test: the committed generated files equal what the generators produce now."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from gwylio.cli.main import cli_verbs
from gwylio.infrastructure.codegen.generate import (
    GLOSSARY_PATH,
    REFERENCE_PATH,
    SCHEMA_DIR,
    TYPESCRIPT_PATH,
    render_generated,
    stale_files,
    write_generated,
)
from gwylio.infrastructure.config.loaders import load_config
from gwylio.infrastructure.config.schemas import SCHEMA_MODELS
from tests.support import PROJECT_ROOT

pytestmark = pytest.mark.integration

GENERATED_MARK = "Generated by `gwylio schema`"


@pytest.fixture(scope="module")
def generated(tmp_path_factory: pytest.TempPathFactory) -> tuple[Path, list[str]]:
    out = tmp_path_factory.mktemp("generated")
    files = render_generated(load_config(PROJECT_ROOT), cli_verbs())
    write_generated(out, files)
    return out, sorted(files)


def test_every_expected_file_is_generated(generated: tuple[Path, list[str]]) -> None:
    _, paths = generated
    expected = {f"{SCHEMA_DIR}/{name}.schema.json" for name in SCHEMA_MODELS}
    expected |= {GLOSSARY_PATH, REFERENCE_PATH, TYPESCRIPT_PATH}
    assert set(paths) == expected
    for contract in ("submission", "sweep", "datecheck"):
        assert f"{SCHEMA_DIR}/{contract}.schema.json" in paths


def test_committed_files_match_the_generators_byte_for_byte(
    generated: tuple[Path, list[str]],
) -> None:
    out, paths = generated
    drifted = [
        path
        for path in paths
        if not (PROJECT_ROOT / path).is_file()
        or (PROJECT_ROOT / path).read_bytes() != (out / path).read_bytes()
    ]
    assert not drifted, f"generated files out of date, run `make schema`: {drifted}"


def test_no_stale_schema_files_are_committed() -> None:
    files = render_generated(load_config(PROJECT_ROOT), cli_verbs())
    assert stale_files(PROJECT_ROOT, files) == []


def test_every_generated_file_says_it_is_generated(generated: tuple[Path, list[str]]) -> None:
    out, paths = generated
    for path in paths:
        head = (out / path).read_text(encoding="utf-8")[:300]
        assert GENERATED_MARK in head, path


def test_generation_is_deterministic() -> None:
    config = load_config(PROJECT_ROOT)
    assert render_generated(config, cli_verbs()) == render_generated(config, cli_verbs())


def test_write_generated_reports_changes_and_dry_run_writes_nothing(tmp_path: Path) -> None:
    files = {"a/b.txt": "one\n"}
    assert [r.changed for r in write_generated(tmp_path, files, dry_run=True)] == [True]
    assert not (tmp_path / "a/b.txt").exists()
    assert [r.changed for r in write_generated(tmp_path, files)] == [True]
    assert [r.changed for r in write_generated(tmp_path, files)] == [False]


def test_reference_lists_every_cli_verb() -> None:
    text = (PROJECT_ROOT / REFERENCE_PATH).read_text(encoding="utf-8")
    for verb, _ in cli_verbs():
        assert f"`gwylio {verb}`" in text


def test_reference_lists_every_value_a_submission_may_carry() -> None:
    text = (PROJECT_ROOT / REFERENCE_PATH).read_text(encoding="utf-8")
    for heading in ("### Disposition outcomes", "### Credibility", "### Indicator states"):
        assert heading in text
    for value in ("`informs_baseline`", "`follow_up`", "`data_release`", "`near_term`"):
        assert value in text


def test_the_submission_schema_names_the_contract_fields() -> None:
    schema = json.loads(
        (PROJECT_ROOT / SCHEMA_DIR / "submission.schema.json").read_text(encoding="utf-8")
    )
    assert schema["properties"]["schema"]["const"] == "gwylio.submission/1"
    assert set(schema["required"]) >= {"schema", "run_id", "analyst", "received_on"}
    update = schema["$defs"]["UpdateEntry"]
    assert "set" in update["properties"]
