"""JSON Schema for every configuration file contract."""

from __future__ import annotations

import json
from collections.abc import Mapping
from typing import Any, Final

from pydantic import BaseModel

__all__ = ["GENERATED_NOTE", "json_schema_documents", "render_json"]

GENERATED_NOTE: Final[str] = (
    "Generated by `gwylio schema` from the Pydantic models registered in "
    "backend/src/gwylio/infrastructure/config/schemas.py. Do not edit by hand."
)
_DIALECT: Final[str] = "https://json-schema.org/draft/2020-12/schema"


def json_schema_documents(
    models: Mapping[str, type[BaseModel]],
) -> dict[str, dict[str, Any]]:
    """One JSON Schema document per model, keyed by schema name."""
    documents: dict[str, dict[str, Any]] = {}
    for name in sorted(models):
        schema = models[name].model_json_schema()
        documents[name] = {
            "$comment": GENERATED_NOTE,
            "$id": f"{name}.schema.json",
            "$schema": _DIALECT,
            **schema,
        }
    return documents


def render_json(document: Mapping[str, Any]) -> str:
    """Stable JSON text: sorted keys, two-space indent, trailing newline."""
    return json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
