"""The generated Markdown documents: the glossary and the skill's reference sheet."""

from __future__ import annotations

from collections.abc import Iterable, Sequence

from gwylio.collection.model import CandidateStatus, Discipline, Reliability
from gwylio.direction.model import Scanability
from gwylio.direction.scanability import CoverageStatus
from gwylio.infrastructure.config.loaders import LoadedConfig
from gwylio.intelligence.datecheck import FindingKind
from gwylio.processing.submission import RUBRIC_VERSION, UPDATABLE_FIELDS
from gwylio.reference.model import Lens
from gwylio.shared.vocabulary import (
    Bucket,
    Credibility,
    Direction,
    DispositionOutcome,
    IndicatorState,
    Level,
    ReportType,
    TimeHorizon,
)

__all__ = ["CliVerb", "glossary_markdown", "reference_markdown"]

CliVerb = tuple[str, str]
"""A command line verb and its one-line help."""


def _generated(source: str) -> str:
    return f"<!-- Generated by `gwylio schema` from {source}. Do not edit by hand. -->\n"


def _cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def _table(headers: Sequence[str], rows: Iterable[Sequence[str]]) -> list[str]:
    lines = [
        "| " + " | ".join(headers) + " |",
        "|" + "|".join("---" for _ in headers) + "|",
    ]
    lines.extend("| " + " | ".join(_cell(cell) for cell in row) + " |" for row in rows)
    return lines


def glossary_markdown(glossary: Sequence[tuple[str, str]]) -> str:
    """``docs/GLOSSARY.md``: every term in alphabetical order."""
    lines = [
        _generated("backend/src/gwylio/shared/glossary.py"),
        "# Glossary",
        "",
        "The ubiquitous language of Gwylio, the Welsh environmental open-source intelligence "
        "(OSINT) system. Code, documents and the analyst skill use these words with these "
        "meanings. To change a definition, edit `backend/src/gwylio/shared/glossary.py` and run "
        "`make schema`.",
        "",
    ]
    for term, definition in sorted(glossary, key=lambda entry: entry[0].casefold()):
        lines.append(f"**{term}**: {definition}")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def reference_markdown(config: LoadedConfig, verbs: Sequence[CliVerb]) -> str:
    """``skill/REFERENCE.md``: every closed value and identifier the analyst skill may use."""
    catalogue = config.catalogue
    lines = [
        _generated("the configuration under config/ and the domain enums"),
        "# Gwylio reference for the analyst skill",
        "",
        "Every closed value and identifier the analyst skill may write into a submission, "
        "and every verb of the `gwylio` command line tool. Values outside these lists are not "
        "valid in a submission. Regenerate with `make schema` after changing configuration.",
        "",
        "## Command line verbs",
        "",
        *_table(["Verb", "What it does"], ((f"`gwylio {name}`", help_) for name, help_ in verbs)),
        "",
        "## Scanability",
        "",
        "How far public, indexed sources can see a requirement at all.",
        "",
        *_table(["Value", "Meaning"], ((f"`{s.value}`", s.meaning) for s in Scanability)),
        "",
        "## Coverage status",
        "",
        "Computed, never written by hand. A blind spot is never rendered as quiet.",
        "",
        *_table(["Value", "Meaning"], ((f"`{c.value}`", c.meaning) for c in CoverageStatus)),
        "",
        "## Disciplines",
        "",
        "The kind of collection that found a hit. Reserved disciplines have no collector yet.",
        "",
        *_table(["Value", "Meaning"], ((f"`{d.value}`", d.meaning) for d in Discipline)),
        "",
        "## Reliability",
        "",
        "The Admiralty reliability of a source. It comes from the source, never from a "
        "submission; the analyst judges credibility (1 to 6) per report.",
        "",
        *_table(["Letter", "Meaning"], ((f"`{r.value}`", r.label) for r in Reliability)),
        "",
        "## Candidate status",
        "",
        "What the collector knew about a candidate's canonical URL. Computed at collection.",
        "",
        *_table(["Value", "Meaning"], ((f"`{c.value}`", c.meaning) for c in CandidateStatus)),
        "",
        "## Submissions",
        "",
        f"A submission is `gwylio.submission/1`, judged against rubric version `{RUBRIC_VERSION}` "
        "(docs/RUBRIC.md). Every `new` candidate of the run needs a disposition and every "
        "`reinforcement` candidate an entry in `reinforcements` (or a disposition); "
        "`seen_before` candidates may have one.",
        "",
        "### Disposition outcomes",
        "",
        *_table(["Value", "Meaning"], ((f"`{o.value}`", o.meaning) for o in DispositionOutcome)),
        "",
        "### Credibility",
        "",
        "The analyst's judgement of one report's information. With the source's reliability it "
        "makes the grading, such as B2.",
        "",
        *_table(["Digit", "Meaning"], ((f"`{int(c)}`", c.label) for c in Credibility)),
        "",
        "### Directions",
        "",
        *_table(["Value", "Meaning"], ((f"`{d.value}`", d.meaning) for d in Direction)),
        "",
        "### Report types, buckets and scores",
        "",
        *_table(
            ["Field", "Values"],
            (
                ("`report_type`", ", ".join(f"`{t.value}`" for t in ReportType)),
                ("`bucket`", ", ".join(f"`{b.value}`" for b in Bucket)),
                (
                    "`scores.evidence`, `scores.novelty`, `scores.confidence`, "
                    "`scores.potential_impact`",
                    ", ".join(f"`{level.value}`" for level in Level),
                ),
                ("`scores.time_horizon`", ", ".join(f"`{h.value}`" for h in TimeHorizon)),
                ("`state_override`", "`matured`, `parked`"),
                ("`updates[].set` keys", ", ".join(f"`{key}`" for key in UPDATABLE_FIELDS)),
            ),
        ),
        "",
        "### Indicator states",
        "",
        "Computed by the lifecycle from sightings. The analyst may set only `matured` or "
        "`parked`, in an update or as a promotion's `state_override`.",
        "",
        *_table(["Value", "Meaning"], ((f"`{s.value}`", s.meaning) for s in IndicatorState)),
        "",
        "## Date check findings",
        "",
        "What `gwylio datecheck` reports. It informs and never blocks.",
        "",
        *_table(["Value", "Meaning"], ((f"`{k.value}`", k.meaning) for k in FindingKind)),
        "",
        "## Lenses and lanes",
        "",
        "Lanes say where a signal was found; requirements say what it means.",
        "",
        *_table(
            ["Lens", "Lanes"],
            (
                (
                    f"`{lens.value}`",
                    ", ".join(f"`{lane.id}`" for lane in catalogue.lanes if lane.lens is lens),
                )
                for lens in Lens
            ),
        ),
        "",
        *_table(
            ["Lane id", "Name", "Lens", "Description"],
            (
                (f"`{lane.id}`", lane.name, f"`{lane.lens.value}`", lane.description)
                for lane in catalogue.lanes
            ),
        ),
        "",
        "## Taxonomy",
        "",
        "Node ids are unique across every axis.",
    ]
    for axis in catalogue.taxonomy.axes:
        lines.extend(["", f"### `{axis.id}`: {axis.name}", ""])
        lines.extend(
            _table(
                ["Node id", "Name", "Kind"],
                ((f"`{node.id}`", node.name, f"`{node.kind.value}`") for node in axis.nodes),
            )
        )
    lines.extend(["", "## Requirement sets"])
    for requirement_set in config.requirement_sets:
        lines.extend(
            [
                "",
                f"### `{requirement_set.id}`: {requirement_set.name}",
                "",
                f"Version {requirement_set.version}. Source: {requirement_set.source_doc}.",
                "",
            ]
        )
        lines.extend(
            _table(
                ["Code", "Id", "Short name", "Scanability", "Expected coverage"],
                (
                    (
                        r.code,
                        f"`{r.id}`",
                        r.short,
                        f"`{r.scanability.value}`",
                        ", ".join(f"`{node}`" for node in r.expected_coverage) or "none",
                    )
                    for r in requirement_set.requirements
                ),
            )
        )
        lines.append("")
        lines.extend(
            _table(
                ["Group id", "Kind", "Name", "Members"],
                (
                    (
                        f"`{g.id}`",
                        f"`{g.kind.value}`",
                        g.name,
                        ", ".join(f"`{member}`" for member in g.members),
                    )
                    for g in requirement_set.groups
                ),
            )
        )
    lines.extend(["", "## Reference catalogues", "", "### Topics", ""])
    lines.extend(_table(["Id", "Name"], ((f"`{t.id}`", t.name) for t in catalogue.topics)))
    lines.extend(["", "### Hazards", ""])
    lines.extend(
        _table(
            ["Id", "Name", "Family"],
            ((f"`{h.id}`", h.name, f"`{h.family}`") for h in catalogue.hazards),
        )
    )
    lines.extend(["", "### Places", ""])
    lines.extend(
        _table(
            ["Id", "Name", "Kind", "Parent"],
            (
                (f"`{p.id}`", p.name, f"`{p.kind.value}`", f"`{p.parent}`" if p.parent else "")
                for p in catalogue.places
            ),
        )
    )
    lines.extend(["", "### Actors", ""])
    lines.extend(
        _table(
            ["Id", "Name", "Kind", "Lane"],
            ((f"`{a.id}`", a.name, f"`{a.kind.value}`", f"`{a.lane}`") for a in catalogue.actors),
        )
    )
    lines.extend(["", "### Sources", ""])
    lines.extend(
        _table(
            ["Id", "Name", "Lane", "Discipline", "Reliability", "Trusted", "Status"],
            (
                (
                    f"`{s.id}`",
                    s.name,
                    f"`{s.lane}`",
                    f"`{s.discipline.value}`",
                    f"`{s.reliability.value}`",
                    "yes" if s.trusted else "no",
                    f"`{s.status.value}`",
                )
                for s in config.sources
            ),
        )
    )
    return "\n".join(lines) + "\n"
