"""The generated Markdown documents: the glossary and the skill's reference sheet."""

from __future__ import annotations

from collections.abc import Iterable, Sequence

from gwylio.direction.model import Scanability
from gwylio.direction.scanability import CoverageStatus
from gwylio.infrastructure.config.loaders import LoadedConfig
from gwylio.reference.model import Lens

__all__ = ["CliVerb", "glossary_markdown", "reference_markdown"]

CliVerb = tuple[str, str]
"""A command line verb and its one-line help."""


def _generated(source: str) -> str:
    return f"<!-- Generated by `gwylio schema` from {source}. Do not edit by hand. -->\n"


def _cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def _table(headers: Sequence[str], rows: Iterable[Sequence[str]]) -> list[str]:
    lines = [
        "| " + " | ".join(headers) + " |",
        "|" + "|".join("---" for _ in headers) + "|",
    ]
    lines.extend("| " + " | ".join(_cell(cell) for cell in row) + " |" for row in rows)
    return lines


def glossary_markdown(glossary: Sequence[tuple[str, str]]) -> str:
    """``docs/GLOSSARY.md``: every term in alphabetical order."""
    lines = [
        _generated("backend/src/gwylio/shared/glossary.py"),
        "# Glossary",
        "",
        "The ubiquitous language of Gwylio, the Welsh environmental open-source intelligence "
        "(OSINT) system. Code, documents and the analyst skill use these words with these "
        "meanings. To change a definition, edit `backend/src/gwylio/shared/glossary.py` and run "
        "`make schema`.",
        "",
    ]
    for term, definition in sorted(glossary, key=lambda entry: entry[0].casefold()):
        lines.append(f"**{term}**: {definition}")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def reference_markdown(config: LoadedConfig, verbs: Sequence[CliVerb]) -> str:
    """``skill/REFERENCE.md``: every closed value and identifier the analyst skill may use."""
    catalogue = config.catalogue
    lines = [
        _generated("the configuration under config/ and the domain enums"),
        "# Gwylio reference for the analyst skill",
        "",
        "Every closed value and identifier the analyst skill may write into a submission, "
        "and every verb of the `gwylio` command line tool. Values outside these lists are not "
        "valid in a submission. Regenerate with `make schema` after changing configuration.",
        "",
        "## Command line verbs",
        "",
        *_table(["Verb", "What it does"], ((f"`gwylio {name}`", help_) for name, help_ in verbs)),
        "",
        "## Scanability",
        "",
        "How far public, indexed sources can see a requirement at all.",
        "",
        *_table(["Value", "Meaning"], ((f"`{s.value}`", s.meaning) for s in Scanability)),
        "",
        "## Coverage status",
        "",
        "Computed, never written by hand. A blind spot is never rendered as quiet.",
        "",
        *_table(["Value", "Meaning"], ((f"`{c.value}`", c.meaning) for c in CoverageStatus)),
        "",
        "## Lenses and lanes",
        "",
        "Lanes say where a signal was found; requirements say what it means.",
        "",
        *_table(
            ["Lens", "Lanes"],
            (
                (
                    f"`{lens.value}`",
                    ", ".join(f"`{lane.id}`" for lane in catalogue.lanes if lane.lens is lens),
                )
                for lens in Lens
            ),
        ),
        "",
        *_table(
            ["Lane id", "Name", "Lens", "Description"],
            (
                (f"`{lane.id}`", lane.name, f"`{lane.lens.value}`", lane.description)
                for lane in catalogue.lanes
            ),
        ),
        "",
        "## Taxonomy",
        "",
        "Node ids are unique across every axis.",
    ]
    for axis in catalogue.taxonomy.axes:
        lines.extend(["", f"### `{axis.id}`: {axis.name}", ""])
        lines.extend(
            _table(
                ["Node id", "Name", "Kind"],
                ((f"`{node.id}`", node.name, f"`{node.kind.value}`") for node in axis.nodes),
            )
        )
    lines.extend(["", "## Requirement sets"])
    for requirement_set in config.requirement_sets:
        lines.extend(
            [
                "",
                f"### `{requirement_set.id}`: {requirement_set.name}",
                "",
                f"Version {requirement_set.version}. Source: {requirement_set.source_doc}.",
                "",
            ]
        )
        lines.extend(
            _table(
                ["Code", "Id", "Short name", "Scanability", "Expected coverage"],
                (
                    (
                        r.code,
                        f"`{r.id}`",
                        r.short,
                        f"`{r.scanability.value}`",
                        ", ".join(f"`{node}`" for node in r.expected_coverage) or "none",
                    )
                    for r in requirement_set.requirements
                ),
            )
        )
        lines.append("")
        lines.extend(
            _table(
                ["Group id", "Kind", "Name", "Members"],
                (
                    (
                        f"`{g.id}`",
                        f"`{g.kind.value}`",
                        g.name,
                        ", ".join(f"`{member}`" for member in g.members),
                    )
                    for g in requirement_set.groups
                ),
            )
        )
    lines.extend(["", "## Reference catalogues", "", "### Topics", ""])
    lines.extend(_table(["Id", "Name"], ((f"`{t.id}`", t.name) for t in catalogue.topics)))
    lines.extend(["", "### Hazards", ""])
    lines.extend(
        _table(
            ["Id", "Name", "Family"],
            ((f"`{h.id}`", h.name, f"`{h.family}`") for h in catalogue.hazards),
        )
    )
    lines.extend(["", "### Places", ""])
    lines.extend(
        _table(
            ["Id", "Name", "Kind", "Parent"],
            (
                (f"`{p.id}`", p.name, f"`{p.kind.value}`", f"`{p.parent}`" if p.parent else "")
                for p in catalogue.places
            ),
        )
    )
    lines.extend(["", "### Actors", ""])
    lines.extend(
        _table(
            ["Id", "Name", "Kind", "Lane"],
            ((f"`{a.id}`", a.name, f"`{a.kind.value}`", f"`{a.lane}`") for a in catalogue.actors),
        )
    )
    return "\n".join(lines) + "\n"
